config/routes.rb
Rails.application.routes.draw do

  resources:tops, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end
  
  root 'tops#index'
  

end

app/models/top.rb
class Top < ActiveRecord::Base
    validates :content, presence: true, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  before_action :set_top, only: [:edit, :update, :destroy]
  
  def index
    @tops = Top.all
  end
  
  def new
    if params[:back]
      @top = Top.new(tops_params)
    else
      @top = Top.new
    end
  end
  
  def confirm
    @top = Top.new(tops_params)
    render :new if @top.invalid?
  end
  
  def create
    @top = Top.new(tops_params)
    if @top.save
      redirect_to tops_path, notice: "つぶやきました！"
    else
      render 'new'
    end
  end
  
  def edit
    #@top = Top.find(params[:id])
  end
  
  def update
    #@top = Top.find(params[:id])
    if @top.update(tops_params)
      redirect_to tops_path, notice: "つぶやきを更新しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    #@top = Top.find(params[:id])
    @top.destroy
    redirect_to tops_path, notice: "つぶやきを削除しました！"
  end
  
  private
    def tops_params
      params.require(:top).permit(:content)
    end
    
    def set_top
      @top = Top.find(params[:id])
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_tops_path
    elsif action_name == 'edit'
      top_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exam01</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Mastodon", root_path, class: "navbar-brand" %>
    </div>

  </div><!-- /.container-fluid -->
</nav>
</header>

<%= yield %>

  <footer>
    <p><a href="https://diveintocode.jp/">運営会社DIVE INTO CODE株式会社</a></p>
    <p>© 2015-2017 Copyright DIVE INTO CODE Corp.</p>
  </footer>

</body>
</html>

app/views/tops/_form.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@top, url: choose_new_or_edit) do |f| %>

  <% if @top.errors.any? %>
    <div id="error_explanation">
      <h2><%= @top.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @top.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%#<%= f.label :content %>
  <br>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit 'つぶやく', class: 'btn btn-primary btn-block' %>
<% end %>
<br>
<%= link_to "つぶやき一覧画面にもどる", tops_path %>

app/views/tops/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、つぶやく。</h3>
      <%= form_for(@top) do |f| %>
      <%= f.hidden_field :content %>
      <p>本文:<%= @top.content %></p>
      <%= f.submit "つぶやく",class: 'btn btn-primary btn-block'  %>
    <% end %>
    <%= form_for(@top, url: new_top_path, method: 'get') do |f| %>
      <%= f.hidden_field :content %>
      <%= f.submit "冷静に見直す？", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/tops/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>前言撤回？？？</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/tops/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>呟き一覧</h1>
    <%= link_to "つぶやく", new_top_path, class: 'btn btn-default' %><br><br>
    <% @tops.each do |top| %>
    <div class="row">
      <p><%= top.content %></p>
      <%= link_to "編集", edit_top_path(top.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", top_path(top.id), method: :delete , data: { confirm: '本当に編集していいですか？' }, class: 'btn btn-default btn-sm btn btn-danger' %><br><br>
    </div>
    <% end %>
  </div>
</div>

app/views/tops/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>とりあえずつぶやく？</h2>
    <%= render 'form' %>
  </div>
</div>